services:
  api:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    networks:
      panteon:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: osiris_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      panteon:

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command:
      - start-dev
      - --import-realm
      - --http-relative-path
      - /auth
    restart: unless-stopped
    init: true
    healthcheck:
      test: cat /proc/net/tcp | grep '00000000:1F90 00000000:0000' || exit 1
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 120s
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./docker/osiris-realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - '8088:8080'
    networks:
      panteon:

  migrate:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy"
    depends_on:
      - postgres
    networks:
      - panteon

networks:
  panteon:
    driver: bridge
    name: panteon
