qa_mode: true
app_url: 'https://mr.melhorenvio.work'
consolidate_queue_delay_time: 4

keycloak:
  auth_server_url: http://localhost:8081/auth
  realm: melhor-rastreio
  client_id: api
  apiRole: '3rdPartyIntegration'
  secret: b8b19a66-8d8d-4f93-8388-ca2c2f6b6fa5
  admin: admin
  admin_password: melhorrastreio
  request_timeout: 5000

database:
  uri: 'postgresql://root:docker@localhost:5432/osiris_db?schema=public'

default_mail_destination: tecnologia-rastreio@melhorenvio.com
